# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - jdr-nest-comunity

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Prepare release artifact
        run: |
          mkdir release
          cp -r dist release/
          cp package*.json release/
          cd release
          npm install --omit=dev

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: release/
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F2ABCC928F554E70B38E06A6ECCC8D12 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D97928D56BA14C65AB2A17CD7B131650 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3FFACCAB954C416D868343FCB9E69A71 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jdr-nest-comunity'
          slot-name: 'Production'
          package: release/
          